<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <useWPF>true</useWPF>
    <Nullable>enable</Nullable>
    <AssemblyName>Flow.Launcher.Plugin.Zoxide</AssemblyName>
    <PackageId>Flow.Launcher.Plugin.Zoxide</PackageId>
    <Authors>WantChane</Authors>
    <PackageProjectUrl>https://github.com/WantChane/Flow.Launcher.Plugin.Zoxide</PackageProjectUrl>
    <RepositoryUrl>https://github.com/WantChane/Flow.Launcher.Plugin.Zoxide</RepositoryUrl>
    <PackageTags>flow-launcher flow-plugin</PackageTags>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="plugin.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
    
  <ItemGroup>
    <Content Include="Images\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Languages\*.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Flow.Launcher.Plugin" Version="5.2.0" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Flow.Launcher.Plugin.Zoxide.Test" />
  </ItemGroup>

</Project>
